AWSTemplateFormatVersion: 2010-09-09
Description: 'DB'

Parameters:
  ProjectPrefix:
    Type: String
  ProjectName:
    Type: String

  VpcId:
    Type: String
    Description: 'VPC Id'

  DBUserSecret:
    Type: String
    Description: 'DB User secret'

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

  DBRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectPrefix}-role-${ProjectName}-db'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/aws-service-role/AmazonRDSServiceRolePolicy

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub '${ProjectPrefix}-db-${ProjectName}'
      Engine: 'mysql'
      DBInstanceClass: db.t4g.micro # Free Tier
      AllocatedStorage: '20' # Free Tier
      PubliclyAccessible: false
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: !Ref DBSecurityGroup
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
