services:
  db:
    image: arm64v8/mysql
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    volumes:
      - dev-db:/var/lib/mysql

  test-db:
    image: arm64v8/mysql
    env_file:
      - ../.env.test.local
    ports:
      - '3307:3306'
    volumes:
      - dev-test-db:/var/lib/mysql-test

volumes:
  dev-db:
  dev-test-db:
